
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jun 27 23:09:21 CEST 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 15;
  public static final int LBRACKET = 25;
  public static final int INCREMENT = 17;
  public static final int CONST = 6;
  public static final int CHAR = 34;
  public static final int NAMESPACE = 4;
  public static final int PERIOD = 21;
  public static final int LPAREN = 23;
  public static final int SEMI = 20;
  public static final int MINUS = 12;
  public static final int DECREMENT = 18;
  public static final int STATIC = 9;
  public static final int RPAREN = 24;
  public static final int RANGE = 29;
  public static final int COMMA = 22;
  public static final int PLUS = 11;
  public static final int MULTIPLY = 14;
  public static final int EOF = 0;
  public static final int RETURN = 7;
  public static final int RBRACKET = 26;
  public static final int EQUAL = 13;
  public static final int NEW = 10;
  public static final int error = 1;
  public static final int NUMBER = 33;
  public static final int IDENT = 35;
  public static final int VOID = 8;
  public static final int COLON = 19;
  public static final int LBRACE = 27;
  public static final int READ = 5;
  public static final int GOTO = 31;
  public static final int RBRACE = 28;
  public static final int PROG = 2;
  public static final int BOOL_CONST = 32;
  public static final int MODUO = 16;
  public static final int MAX = 30;
  public static final int PRINT = 3;
}

